"""Apply clinical / research / archive packaging profiles to conversion outputs."""

from __future__ import annotations

import json
import logging
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from neuro_pipeline import __version__
from neuro_pipeline.export.profiles import ExportProfileId, get_profile
from neuro_pipeline.provenance.hash_manager import HashManager

LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class ExportProfileResult:
    profile: str
    output_dir: Path
    files_written: list[Path] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    message: str = ""


class ExportProfileManager:
    """Package an existing conversion output according to a named profile.

    Never modifies source DICOM. Never overwrites existing destination files
    without using a unique name.
    """

    def __init__(self, hash_manager: HashManager | None = None) -> None:
        self.hash_manager = hash_manager or HashManager()

    def apply(
        self,
        *,
        input_dir: Path | str,
        output_dir: Path | str,
        profile: str,
        dataset_name: str = "NeuroPipeline Dataset",
    ) -> ExportProfileResult:
        profile_obj = get_profile(profile)
        src = Path(input_dir)
        dest = Path(output_dir)
        if not src.is_dir():
            raise FileNotFoundError(f"Conversion output not found: {src}")
        dest.mkdir(parents=True, exist_ok=True)

        if profile_obj.id == ExportProfileId.BIDS:
            return self._export_bids(src, dest, dataset_name=dataset_name)
        if profile_obj.id == ExportProfileId.CLINICAL:
            return self._export_clinical(src, dest)
        return self._export_archive(src, dest)

    def _export_bids(
        self, src: Path, dest: Path, *, dataset_name: str
    ) -> ExportProfileResult:
        written: list[Path] = []
        skipped: list[str] = []
        # Copy NIfTI tree except staging/derivatives noise when possible
        written.extend(self._copy_tree(src, dest, skipped=skipped))

        dd = dest / "dataset_description.json"
        if dd.exists():
            skipped.append(str(dd.name))
        else:
            payload = {
                "Name": dataset_name,
                "BIDSVersion": "1.8.0",
                "DatasetType": "raw",
                "GeneratedBy": [
                    {
                        "Name": "NeuroPipeline DICOM Converter",
                        "Version": __version__,
                        "Description": "Research BIDS export profile",
                    }
                ],
                "License": "Insufficient information — fill before public release",
            }
            dd.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
            written.append(dd)

        parts = dest / "participants.tsv"
        if parts.exists():
            skipped.append(parts.name)
        else:
            # Discover sub-* folders
            subjects = sorted(
                p.name for p in dest.iterdir() if p.is_dir() and p.name.startswith("sub-")
            )
            lines = ["participant_id\tsex\tage"]
            if not subjects:
                lines.append("sub-unknown\tn/a\tn/a")
            else:
                lines.extend(f"{s}\tn/a\tn/a" for s in subjects)
            parts.write_text("\n".join(lines) + "\n", encoding="utf-8")
            written.append(parts)

        readme = dest / "README"
        if readme.exists():
            skipped.append(readme.name)
        else:
            stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
            readme.write_text(
                (
                    f"{dataset_name}\n"
                    f"{'=' * len(dataset_name)}\n\n"
                    f"Research BIDS package generated by NeuroPipeline v{__version__} "
                    f"on {stamp}.\n"
                    "Source DICOM data were not modified.\n"
                ),
                encoding="utf-8",
            )
            written.append(readme)

        return ExportProfileResult(
            profile="bids",
            output_dir=dest,
            files_written=written,
            skipped=skipped,
            message="Research BIDS profile applied",
        )

    def _export_clinical(self, src: Path, dest: Path) -> ExportProfileResult:
        written: list[Path] = []
        skipped: list[str] = []
        nifti_root = dest / "nifti"
        nifti_root.mkdir(parents=True, exist_ok=True)
        for path in src.rglob("*"):
            if not path.is_file():
                continue
            if path.name.startswith("."):
                continue
            # Skip staging / logs / personal-looking files
            if any(part in {"_staging", "logs", "derivatives"} for part in path.parts):
                continue
            lower = path.name.lower()
            if lower.endswith("metadata.json") or lower.endswith("_metadata.json"):
                try:
                    data = json.loads(path.read_text(encoding="utf-8"))
                except Exception:
                    continue
                if not isinstance(data, dict):
                    continue
                for key in (
                    "patient_id",
                    "patient_age",
                    "patient_sex",
                    "PatientName",
                    "patient_name",
                ):
                    data.pop(key, None)
                target = nifti_root / "metadata_clinical.json"
                if target.exists():
                    target = _unique_path(nifti_root / f"{path.stem}_clinical.json")
                target.write_text(
                    json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8",
                )
                written.append(target)
            elif lower.endswith((".nii", ".nii.gz", ".json", ".bval", ".bvec")):
                # Strip patient identifiers from filenames when obvious? keep stem, copy only
                rel = path.relative_to(src)
                target = nifti_root / rel.name
                target = _unique_path(target)
                shutil.copy2(path, target)
                written.append(target)

        manifest = dest / "clinical_manifest.json"
        if not manifest.exists():
            manifest.write_text(
                json.dumps(
                    {
                        "profile": "clinical",
                        "software": f"NeuroPipeline {__version__}",
                        "files": [str(p.relative_to(dest)) for p in written],
                        "note": "Minimal metadata; no PatientName exported",
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            written.append(manifest)
        return ExportProfileResult(
            profile="clinical",
            output_dir=dest,
            files_written=written,
            skipped=skipped,
            message="Clinical profile applied (no PHI fields)",
        )

    def _export_archive(self, src: Path, dest: Path) -> ExportProfileResult:
        written: list[Path] = []
        skipped: list[str] = []
        data_dir = dest / "data"
        logs_dir = dest / "logs"
        data_dir.mkdir(parents=True, exist_ok=True)
        logs_dir.mkdir(parents=True, exist_ok=True)

        for path in src.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(src)
            lower = path.name.lower()
            if lower.endswith((".log", ".txt")) or "log" in path.parts:
                target = logs_dir / path.name
                target = _unique_path(target)
                shutil.copy2(path, target)
                written.append(target)
            elif lower.endswith(
                (".nii", ".nii.gz", ".json", ".bval", ".bvec", ".html", ".tsv")
            ) or path.name in {"README", "participants.tsv"}:
                target = data_dir / rel
                target.parent.mkdir(parents=True, exist_ok=True)
                if target.exists():
                    skipped.append(str(rel))
                    continue
                shutil.copy2(path, target)
                written.append(target)

        # Checksums
        digest, records = self.hash_manager.hash_folder(data_dir)
        checksums = dest / "checksums.sha256"
        if checksums.exists():
            skipped.append(checksums.name)
        else:
            lines = [f"{r['hash']}  {r['path']}" for r in records]
            lines.append(f"# aggregate {digest}")
            checksums.write_text("\n".join(lines) + "\n", encoding="utf-8")
            written.append(checksums)

        meta = dest / "archive_manifest.json"
        if not meta.exists():
            meta.write_text(
                json.dumps(
                    {
                        "profile": "archive",
                        "software": f"NeuroPipeline {__version__}",
                        "created": datetime.now(timezone.utc).isoformat(),
                        "aggregate_sha256": digest,
                        "file_count": len(records),
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            written.append(meta)

        return ExportProfileResult(
            profile="archive",
            output_dir=dest,
            files_written=written,
            skipped=skipped,
            message="Archive profile applied with checksums",
        )

    def _copy_tree(
        self, src: Path, dest: Path, *, skipped: list[str]
    ) -> list[Path]:
        written: list[Path] = []
        for path in src.rglob("*"):
            if not path.is_file():
                continue
            if any(part == "_staging" for part in path.parts):
                continue
            rel = path.relative_to(src)
            target = dest / rel
            if target.exists():
                skipped.append(str(rel))
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)
            written.append(target)
        return written


def _unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    stem, suffix = path.stem, path.suffix
    # handle .nii.gz
    if path.name.endswith(".nii.gz"):
        stem = path.name[: -len(".nii.gz")]
        suffix = ".nii.gz"
    n = 1
    while True:
        candidate = path.with_name(f"{stem}_v{n}{suffix}")
        if not candidate.exists():
            return candidate
        n += 1
